import { DrawProof } from '@maude/canvas-lib';

// AUTO-GENERATED by `maude design draw-proof` — render/verify harness for one
// mark. Lives under _draw/ (gitignored); safe to delete + regenerate.
const MARK = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>maude</title><desc>maude mark — a selected node with an agent spark</desc><rect width="16" height="16" x="8" y="8" fill="none" stroke="currentColor" stroke-width="2.6" rx="4"/><g fill="currentColor"><rect width="6.4" height="6.4" x="22.8" y="2.8" rx="1.8"/><rect width="6.4" height="6.4" x="2.8" y="22.8" rx="1.8"/><rect width="6.4" height="6.4" x="22.8" y="22.8" rx="1.8"/></g><path fill="currentColor" d="m6 .6 2.48 2.92L11.4 6 8.48 8.48 6 11.4 3.52 8.48.6 6l2.92-2.48z"/></svg>`;

export default function DrawProofCanvas() {
  return (
    <DrawProof name="maude-mark-c1" mark={<span dangerouslySetInnerHTML={{ __html: MARK }} />} />
  );
}
