import { DrawProof } from '@maude/canvas-lib';

// AUTO-GENERATED by `maude design draw-proof` — render/verify harness for one
// mark. Lives under _draw/ (gitignored); safe to delete + regenerate.
const MARK = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>maude</title><desc>maude mark — selected node with an agent spark (favicon)</desc><rect width="16" height="16" x="8" y="8" fill="none" stroke="currentColor" stroke-width="2.6" rx="4"/><rect width="6.4" height="6.4" x="22.8" y="22.8" fill="currentColor" rx="1.8"/><path fill="currentColor" d="m5.4 0 2.48 2.92L10.8 5.4 7.88 7.88 5.4 10.8 2.92 7.88 0 5.4l2.92-2.48z"/></svg>`;

export default function DrawProofCanvas() {
  return (
    <DrawProof name="maude-mark-fav" mark={<span dangerouslySetInnerHTML={{ __html: MARK }} />} />
  );
}
