import { DrawProof } from '@maude/canvas-lib';

// AUTO-GENERATED by `maude design draw-proof` — render/verify harness for one
// mark. Lives under _draw/ (gitignored); safe to delete + regenerate.
const MARK = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>maude</title><desc>maude mark — a selected node with an agent spark</desc><rect width="16" height="16" x="8" y="8" fill="none" stroke="currentColor" stroke-width="2.6" rx="4"/><g fill="currentColor"><rect width="6.4" height="6.4" x="22.8" y="2.8" rx="1.8"/><rect width="6.4" height="6.4" x="2.8" y="22.8" rx="1.8"/><rect width="6.4" height="6.4" x="22.8" y="22.8" rx="1.8"/></g><path fill="currentColor" d="m6.2 1.2 2.12 2.88L11.2 6.2 8.32 8.32 6.2 11.2 4.08 8.32 1.2 6.2l2.88-2.12z"/></svg>`;

export default function DrawProofCanvas() {
  return (
    <DrawProof name="maude-mark" mark={<span dangerouslySetInnerHTML={{ __html: MARK }} />} />
  );
}
