import { DesignCanvas, DCSection, DCArtboard, VideoComp } from '@maude/canvas-lib';
import {
  AbsoluteFill,
  Easing,
  OffthreadVideo,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';
import { TransitionSeries, linearTiming } from '@remotion/transitions';
import { fade } from '@remotion/transitions/fade';

// feature-footage-analysis-director dogfood — generated by /design:reel's codegen
// contract (skill footage-director) from alligators-reel.edl.json, TRIMMED from
// the director's original 35 beats to 24 — the frame-step export path (the one
// that reliably renders; see the mp4-whole-comp-render hang note below) caps at
// MAX_FRAMES=900 (30s @ 30fps, apps/studio/exporters/video.ts), and the full
// 35-beat cut (1143 frames / 38.1s) would have its ENDING silently truncated by
// that cap. Trim removes 11 of the most redundant mid-cut "breakaway run" shots
// from the action-barrage block (the beats are already exhausting the same
// visual idea — plenty of variety survives) and shortens celebration-pop by 12f,
// while preserving the full narrative arc: cold open → hook → grind (DŘINA) →
// speed (RYCHLOST) → action barrage → celebration → huddle (SRDCE) → coach
// (BRATRSTVÍ) → the literal "join us" ask → CTA close → crest stinger — all of
// which land in the last third and would otherwise be cut off. One LITERAL
// <TransitionSeries.Sequence> per beat — never .map() (the Timeline reads this
// file as text). TOTAL is a literal sum so the Timeline can resolve it too.
const FPS = 30;
const XF = 15; // the 3 breath-fade seams (grind block / squad huddle / closing CTA)
const TOTAL =
  70 +
  34 +
  28 +
  48 +
  50 +
  34 +
  30 +
  26 +
  30 +
  40 +
  28 +
  24 +
  22 +
  20 +
  20 +
  18 +
  22 +
  20 +
  36 +
  66 +
  48 +
  56 +
  70 +
  72 -
  XF -
  XF -
  XF;

// ── shared beat components (frame-driven only — the determinism iron law) ────

/** Punch-in + contrast/vignette treatment wrapped around every clip. */
const Clip = ({ src, startFrom }: { src: string; startFrom: number }) => {
  const frame = useCurrentFrame();
  const scale = interpolate(frame, [0, 10], [1.06, 1], {
    extrapolateRight: 'clamp',
    easing: Easing.out(Easing.cubic),
  });
  return (
    <AbsoluteFill style={{ overflow: 'hidden', background: '#000' }}>
      <div style={{ position: 'absolute', inset: 0, transform: `scale(${scale})` }}>
        <OffthreadVideo
          src={src}
          startFrom={startFrom}
          style={{
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            filter: 'contrast(1.12) saturate(1.15) brightness(0.96)',
          }}
        />
      </div>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          boxShadow: 'inset 0 0 220px rgba(0,0,0,0.55)',
          pointerEvents: 'none',
        }}
      />
    </AbsoluteFill>
  );
};

/** Big kinetic centered title (opener / value-words / closing CTA). */
const KineticTitle = ({ text, big }: { text: string; big?: boolean }) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();
  const enter = spring({ frame, fps, config: { damping: 14, mass: 0.5, stiffness: 180 } });
  const scale = interpolate(enter, [0, 1], [0.85, 1]);
  const opacity = interpolate(
    frame,
    [0, 8, durationInFrames - 8, durationInFrames],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );
  return (
    <AbsoluteFill
      style={{
        justifyContent: 'center',
        alignItems: 'center',
        background: 'linear-gradient(180deg, rgba(0,0,0,0) 40%, rgba(0,0,0,0.55) 100%)',
      }}
    >
      <div style={{ transform: `scale(${scale})`, opacity, textAlign: 'center' }}>
        <div
          style={{
            fontSize: big ? 84 : 60,
            fontWeight: 900,
            color: '#fff',
            letterSpacing: 4,
            textShadow: '0 6px 40px rgba(0,0,0,0.65), 0 2px 0 #0a0a0a',
            fontFamily: 'system-ui, -apple-system, "Segoe UI", sans-serif',
          }}
        >
          {text}
        </div>
        <div
          style={{
            marginTop: 16,
            height: 6,
            width: 110,
            background: 'linear-gradient(90deg,#ff7a1a,#0fb59a)',
            marginLeft: 'auto',
            marginRight: 'auto',
            borderRadius: 3,
          }}
        />
      </div>
    </AbsoluteFill>
  );
};

/** Bottom-left lower-third (named moment / brand line). */
const LowerThird = ({ text }: { text: string }) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();
  const enter = spring({ frame, fps, config: { damping: 16 } });
  const x = interpolate(enter, [0, 1], [-60, 0]);
  const opacity = interpolate(
    frame,
    [0, 6, durationInFrames - 6, durationInFrames],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );
  return (
    <AbsoluteFill style={{ justifyContent: 'flex-end', padding: 64 }}>
      <div
        style={{
          transform: `translateX(${x}px)`,
          opacity,
          display: 'inline-flex',
          alignItems: 'center',
          gap: 14,
        }}
      >
        <div style={{ width: 6, height: 40, background: '#ff7a1a', borderRadius: 3 }} />
        <div
          style={{
            fontSize: 24,
            fontWeight: 800,
            color: '#fff',
            textShadow: '0 3px 18px rgba(0,0,0,0.7)',
            letterSpacing: 1,
            fontFamily: 'system-ui, -apple-system, "Segoe UI", sans-serif',
          }}
        >
          {text}
        </div>
      </div>
    </AbsoluteFill>
  );
};

// ── the cut — 24 literal beats (trimmed from the director's 35-beat edl.json) ─

const Trailer = () => (
  <AbsoluteFill style={{ background: '#000' }}>
    <TransitionSeries>
      <TransitionSeries.Sequence name="cold-open-doorway" durationInFrames={70}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(0.7 * FPS)} />
        <KineticTitle text="ALLIGATORS BRNO" big />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="team-walkout" durationInFrames={34}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(5 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="hook-tackle" durationInFrames={28}>
        <Clip src="assets/66c0d998.mp4" startFrom={Math.round(3.8 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="locker-room-scream" durationInFrames={48}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(32 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: XF })} />

      <TransitionSeries.Sequence name="grind-drills" durationInFrames={50}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(9.6 * FPS)} />
        <KineticTitle text="DŘINA" />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="bench-press" durationInFrames={34}>
        {/* shifted 10.1s → 11.3s: dense re-probe found a baked "CHCEŠ MAKAT A
            UČIT SE?" title card at ~10s (between two of the promo's OWN
            interstitial cards) that the original 12-frame sparse sample
            straddled and missed — 11.3s lands on clean bench-press footage. */}
        <Clip src="assets/66c0d998.mp4" startFrom={Math.round(11.3 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="battle-ropes" durationInFrames={30}>
        <Clip src="assets/66c0d998.mp4" startFrom={Math.round(16.8 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="agility-drill" durationInFrames={26}>
        <Clip src="assets/66c0d998.mp4" startFrom={Math.round(13.4 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="line-fire-off" durationInFrames={30}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(18.4 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="hero-run-45" durationInFrames={40}>
        <Clip src="assets/314d43a3.mp4" startFrom={Math.round(90.2 * FPS)} />
        <KineticTitle text="RYCHLOST" />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="breakaway-4" durationInFrames={28}>
        <Clip src="assets/2e81036d.mp4" startFrom={Math.round(261 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="live-scramble" durationInFrames={24}>
        <Clip src="assets/2e81036d.mp4" startFrom={Math.round(39 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="friday-lights-run" durationInFrames={22}>
        <Clip src="assets/6f213920.mp4" startFrom={Math.round(130 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="airborne-tackle" durationInFrames={20}>
        <Clip src="assets/2e81036d.mp4" startFrom={Math.round(212 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="sunlit-tackle" durationInFrames={20}>
        <Clip src="assets/9cab63a9.mp4" startFrom={Math.round(44 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="line-clash" durationInFrames={18}>
        <Clip src="assets/2e81036d.mp4" startFrom={Math.round(163 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="dusk-pursuit" durationInFrames={22}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(36.5 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="goal-line-stand" durationInFrames={20}>
        <Clip src="assets/2e81036d.mp4" startFrom={Math.round(461 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="celebration-pop" durationInFrames={36}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(45.6 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: XF })} />

      <TransitionSeries.Sequence name="squad-huddle-flags" durationInFrames={66}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(49.9 * FPS)} />
        <KineticTitle text="SRDCE" />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="coach-moment" durationInFrames={48}>
        <Clip src="assets/9cab63a9.mp4" startFrom={Math.round(168 * FPS)} />
        <LowerThird text="BRATRSTVÍ" />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="join-us-ask" durationInFrames={56}>
        <Clip src="assets/66c0d998.mp4" startFrom={Math.round(6.9 * FPS)} />
      </TransitionSeries.Sequence>

      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: XF })} />

      <TransitionSeries.Sequence name="walk-to-camera-cta" durationInFrames={70}>
        <Clip src="assets/74678a8e.mp4" startFrom={Math.round(54.3 * FPS)} />
        <KineticTitle text="STAŇ SE ALLIGATOREM" big />
      </TransitionSeries.Sequence>

      <TransitionSeries.Sequence name="crest-stinger" durationInFrames={72}>
        <Clip src="assets/9cab63a9.mp4" startFrom={Math.round(271.5 * FPS)} />
        <LowerThird text="alligators.cz" />
      </TransitionSeries.Sequence>
    </TransitionSeries>
  </AbsoluteFill>
);

export default function Canvas() {
  return (
    <DesignCanvas>
      <DCSection title="Alligators Brno — Recruiting Trailer">
        <DCArtboard id="trailer" label="Trailer" width={1280} height={720}>
          <VideoComp component={Trailer} durationInFrames={TOTAL} fps={FPS} width={1280} height={720} />
        </DCArtboard>
      </DCSection>
    </DesignCanvas>
  );
}
