import type { Metadata } from 'next';
import { type WhatsNewEntry, WhatsNewFeed } from '@/components/mdcc/whats-new-feed';
import whatsNewJson from '@/lib/whats-new.json';

export const metadata: Metadata = {
  title: "What's New · Maude",
  description: 'User-facing Maude updates — the same feed surfaced inside the canvas browser.',
};

// `whats-new.json` is regenerated by site/scripts/build-whats-new.mjs from the
// dev-server feed (plugins/design/dev-server/whats-new.json). TS widens the
// imported JSON's literal strings, so re-narrow at the trust boundary.
const feed = whatsNewJson as unknown as {
  generated: string;
  version: string;
  entries: WhatsNewEntry[];
};

export default function WhatsNewPage() {
  return <WhatsNewFeed generated={feed.generated} version={feed.version} entries={feed.entries} />;
}
