import type { Metadata } from 'next';
import { type CurrentPhase, type Phase, RoadmapTimeline } from '@/components/mdcc/roadmap-timeline';
import roadmapJson from '@/lib/roadmap.json';

export const metadata: Metadata = {
  alternates: { canonical: '/roadmap' },
  title: 'Roadmap · Maude',
  description: 'Past, present, and planned phases of Maude development.',
};

// `roadmap.json` is regenerated by site/scripts/build-roadmap.mjs from .ai/.
// TS widens the imported JSON's literal strings (status, etc.) to `string`,
// so we re-narrow here at the trust boundary.
const roadmap = roadmapJson as unknown as {
  generated: string | null; // deterministic: newest phase date (see build-roadmap.mjs)
  currentPhase: CurrentPhase;
  phases: Phase[];
};

export default function RoadmapPage() {
  return (
    <RoadmapTimeline
      phases={roadmap.phases}
      currentPhase={roadmap.currentPhase}
      generated={roadmap.generated}
    />
  );
}
